### ISSUE TITLE
Not appearing as option in Steam

### ISSUE THREAD

**Issue by Yaakoss** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#110]
Fresh install of Debian (today). Steam and SteamTinkerLaunch are the only installed flatpak apps. Nothing has been changed on permissions but SteamtinkerLaunch does not appear in Steam.

**Comment by HanPrower** [comment]
Maybe Debian has some weird defaults?

Just try adding it manually with:
`flatpak run --command="/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch" --file-forwarding com.valvesoftware.Steam compat add`

**Comment by Yaakoss** [comment]
it worked :)))))) Thank you very much.

**Comment by youalreadydid** [comment]
this command also fixed the same issue on Fedora 38

for reference, I manually installed `yad` (`sudo dnf install yad`) before, so I'm not sure if you'll need it too.

**Comment by sonic2kk** [comment]
Sorry to bump a closed issue. Another user recently had to do this as well. Is there anything from my side that can be done about this? It seems like the `compat add` command is not being executed on Flatpak installation, though STL should be doing it inside of its `setflatpak` option.

Unless this is distribution-specific? I don't use Flatpak Steam but I did test briefly on my laptop with Arch Linux some time ago, and I didn't have to do anything back then.

**Comment by noey-drew** [comment]
This fix worked for me as well on Debian 12, nood question here:

How do I do the same thing but with tinkerlaunch beta?

**Comment by sonic2kk** [comment]
If you're talking about the Flatpak beta, you'll need to install the Flatpak from the Beta channel.

If you're referring to SteamTinkerLaunch-git, there is no Flatpak build for SteamTinkerLaunch-git. The Flatpak beta channel is not intended to be a SteamTinkerLaunch-git channel. It may be possible to manually replace the STL files in the Flatpak directory with ones cloned from the repo, but that's pretty hacky and is almost certainly not advisable.

There is no official way of using SteamTinkerLaunch-git with Flatpak Steam.

**Comment by noey-drew** [comment]
I installed it through the flathub beta, I'm wondering if there is a command similar to what @HanPrower posted that can add it manually

**Comment by sonic2kk** [comment]
Does `flatpak run --command="/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch" --file-forwarding com.valvesoftware.Steam compat add` not work for the beta?

**Comment by noey-drew** [comment]
My mistake, it works fine.

**Comment by sonic2kk** [comment]
Could this be related to the path that STL resolves the Flatpak to when running `compat add`? There was a PR recently that had to change where some modding tools' `.desktop` files point to as the realpath was not correct (sonic2kk/steamtinkerlaunch#880).

**Comment by HanPrower** [comment]
> Could this be related to the path that STL resolves the Flatpak to when running `compat add`? There was a PR recently that had to change where some modding tools' `.desktop` files point to as the realpath was not correct for Flatpak ([sonic2kk/steamtinkerlaunch#880](https://github.com/sonic2kk/steamtinkerlaunch/pull/880)).

The differing factor is that one command is run inside the sandbox and one is ran outside.

If you run `ls` on the Flatpak path you get:
```
flatpak run --command=ls com.valvesoftware.Steam /app/utils/steamtinkerlaunch/bin/
7za         composite  git               git-upload-archive  innoextract    mogrify  pehash  pescan  rsync      steamtinkerlaunch  xwininfo
animate     conjure    git-cvsserver     git-upload-pack     jq             montage  peldd   pesec   rsync-ssl  stream             xxd
cabextract  convert    git-receive-pack  identify            magick         ofs2rva  pepack  pestr   rva2ofs    xdotool            yad
compare     display    git-shell         import              magick-script  pedis    peres   readpe  scalar     xprop
```

So it exists as expected internally.

However, technically I don't see why running everything with the external variation wouldn't work anyway, and, probably, simply makes more sense...

**Comment by LostWarriorr** [comment]
Currently having this issue on Debian (KDE Wayland) but also having an additional issue of the command not working due to it not finding xrandr which is interesting. Custom versions of Proton installed through ProtonUp work fine.

`flatpak run --command="/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch" --file-forwarding com.valvesoftware.Steam compat add

Wed May 29 10:49:59 AM CDT 2024 ERROR - checkIntDeps - xrandr not found!

Wed May 29 10:49:59 AM CDT 2024 ERROR - checkIntDeps - Above programs need to be installed to use 'steamtinkerlaunch'

Wed May 29 10:49:59 AM CDT 2024 ERROR - checkIntDeps The dependency check can be disabled by enabling 'SKIPINTDEPCHECK' - exiting now`

**Comment by HanPrower** [comment]
So finally got around to properly checking this and it appears that possibly it was never working properly (or if it ever did it broke...). Maybe I misunderstood how the tool was meant to be added to appear correctly and somehow I just ended up with the files elsewhere.

Not sure...

Either way the closing commit above should fix it.

Note that if this fix does work correctly (I did test it, it does seem to work...), you might need to go to your Steam `compatibilitytools.d` folder and remove the SteamTinkerLaunch folder the command installed:
`flatpak run --command="/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch" --file-forwarding com.valvesoftware.Steam compat del`

This won't break any settings or anything, just means the tool isn't "physically" installed to the `compatibilitytools.d` and is instead installed "magically" with merge-dirs (like it was always meant to be!).

The update can take a few hours to appear via `flatpak update` so if come the 22nd June the issue persists please let me know! :)
