### ISSUE TITLE
Wiki request: Add flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam compat add

### ISSUE THREAD

**Issue by reddragonmps** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#123]
Today I needed to use SteamTinkerLaunch for one of my games and realized compatibility tools symlink had not been created. I searched through the wiki but did not find the solution I was looking for. Well, this is it. Use the `--command` argument to run SteamTinkerLaunch exectuable inside Steam Flatpak's enviroment. I think this needs to be added to the wiki because I have faced this same problem previously. Maybe in a troubleshooting section, like this:

Troubleshooting

If you don't find SteamTinkerLaunch under Steam's compatibility tools (make sure you have Steam Flatpak installed), you need to create the symlink like in the other packaged releases. To do this you need to run `flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam compat add`, then restart Steam. SteamTinkerLaunch should be listed now.

**Comment by HanPrower** [comment]
This repo isn't responsible for the STL wiki.

If you want anything adding you'll need to post over on the main repo. The best place is probably in the main discussion issue: https://github.com/sonic2kk/steamtinkerlaunch/issues/27

Suffice to say what you're stating is not meant to be an issue, it doesn't happen for everyone that it's not being added as a compatibility tool automatically, but it seems to be happening more and more, so I will have to deep-dive it and try and route it out properly.

#110 is basically the same issue (minus the wiki request), so I'll close this just as I can't edit the Wiki and we don't need 2 issues open for basically the same general breakage.
