### ISSUE TITLE
STL doesn't seem to be able to find MangoHud.

### ISSUE THREAD

**Issue by LostWarriorr** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#162]
Fresh install of Debian sid XFCE. 

STL doesn't seem to be able to find Mangohud judging by the mangohud binary option reading as (none). Launch a game using the mangohud %command% makes it launch as normal. Not sure if this is another offshoot of steam not being able to recognize STL correctly and needing a command the make it visible.

I'm not sure if this is at all related to [#137](https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/137) but could be another issue in PATH generation.

**Comment by HanPrower** [comment]
If I start from a blank config it finds Mangohud just fine.

Have you got the flatpak for Mangohud installed?

**Comment by LostWarriorr** [comment]
Yes as said mangohud %command% works just fine. STL is not able to launch it however.

**Comment by HanPrower** [comment]
If you edit `default_template.conf` (or a gamecfg) for the variable to be:
`MAHUBIN="/usr/lib/extensions/vulkan/MangoHud/bin/mangohud"`

Does it work?

My STL log seems to show that it finds it in the `$PATH` just fine.

**Comment by LostWarriorr** [comment]
Yes that appears to work fine and should fix the issue.

What appears to be happening is for whatever reason the game directory is getting passed to the MAHUBIN.

`MAHUBIN="/media/(USER)/Corsair MP510 NVME/SteamLibrary/steamapps/common/AbioticFactor/none`

MAHUBIN in the default config was blank however

`MAHUBIN=""`

**Comment by HanPrower** [comment]
From the steamtinkerlaunch script it appears to assume the binary name of `mangohud`, so for yours to be blank seems odd (https://github.com/sonic2kk/steamtinkerlaunch/blob/master/steamtinkerlaunch#L319).

I could be wrong, but I don't think STL tries to discover MangoHUD itself, it just assumes the binary name and that's it.

I'm going to have to assume this is a weird edge-case configuration quirk and not a `$PATH` issue (as Steam definitely seems to see the mangohud path when I run steam via terminal) and STL seems to assume the binary name.

Steam log: `DEBUG:root:Addding /usr/lib/extensions/vulkan/MangoHud/bin to PATH`
