### ISSUE TITLE
Can we bypass the root user check?

### ISSUE THREAD

**Issue by roostorx** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#194]
![image](https://github.com/user-attachments/assets/b458723b-88e4-4fd6-b0bf-08e5cf75e906)
I am running flatpak STL on flatpak Steam in Batocera where the default user is root.  I realize this isn't ideal but STL won't launch when flatpak Steam launches because of a root user check.  Admittedly, I do not know a lot about flatpak stuff.  I found the STL launcher here /app/utils/steamtinkerlaunch/bin and I found what I think is the root user check at the end of the file.  However, it's read only so I can't comment it out.   I realize this is more of a Batocera issue because they run everything as root, but didn't know if there was a way to bypass that check on the flatpak side.

**Comment by HanPrower** [comment]
Just modify the `steamtinkerlaunch` file as root, and save it if you really need to do something so silly.

Regardless, as this isn't an actual issue with the Flatpak I'm going to close this.
