### ISSUE TITLE
General usage in readme?

### ISSUE THREAD

**Issue by scramble45** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#32]
Whats the general usage command for this? I assumed I could just run it: 
`flatpak run com.valvesoftware.Steam.Utility.steamtinkerlaunch`

**However that results in:**
```
~$ flatpak -v run com.valvesoftware.Steam.Utility.steamtinkerlaunch 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/r0r0/.local/share/flatpak
F: Opening user flatpak installation at path /home/r0r0/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/r0r0/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/com.valvesoftware.Steam.Utility.steamtinkerlaunch/x86_64/stable/7517a39e9a346f8848d60c9c7b27dae40c46d47b9e449d6e6a9232145856fa49/files/lib32 does not exist
F: /var/lib/flatpak/runtime/com.valvesoftware.Steam.Utility.steamtinkerlaunch/x86_64/stable/7517a39e9a346f8848d60c9c7b27dae40c46d47b9e449d6e6a9232145856fa49/files/lib64 does not exist
F: /var/lib/flatpak/runtime/com.valvesoftware.Steam.Utility.steamtinkerlaunch/x86_64/stable/7517a39e9a346f8848d60c9c7b27dae40c46d47b9e449d6e6a9232145856fa49/files/sbin does not exist
F: Cleaning up unused container id 1733064830
F: Allocated instance id 1384137150
F: Add defaults in dir /com/valvesoftware/Steam/Utility/steamtinkerlaunch/
F: Add locks in dir /com/valvesoftware/Steam/Utility/steamtinkerlaunch/
F: Disallowing ipc access
F: Disallowing network access
F: Running 'bwrap --args 34 xdg-dbus-proxy --args=36'
F: Running 'bwrap --args 34 /bin/sh'
bwrap: execvp /bin/sh: No such file or directory
```

How can I get this to work and take in arguments?

**Comment by HanPrower** [comment]
It's automatically installed as a Compatibility Tool for Steam Flatpak, you just have to select to use it for a game or a global Steam Compatibility Tool.

**Comment by HanPrower** [comment]
I added a Usage section to the README :+1:

**Comment by scramble45** [comment]
Saw this got closed, the usage is still unclear. I should be able to pass arguments to this via directly as one does with the non flatpak version. In my particular case I want to add a non-steam game using the flatpak version. I will update my comment with usage shortly, can this be reopened or better explained on how todo what I'm asking as I know its possible?

**Comment by HanPrower** [comment]
STL lives inside the Steam runtime. You can't run it directly.

`flatpak run --command="/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch" --file-forwarding com.valvesoftware.Steam <command>`

e.g.
`flatpak run --command="/app/utils/steamtinkerlaunch/bin/steamtinkerlaunch" --file-forwarding com.valvesoftware.Steam compat add`
(not that you need to ever run compat add as it's installed as a Steam compatibility tool by default).

Even with non-Steam games you can still just select a Compatibility Tool from the game's Properties to bring up the STL UI. It's easier than using commands.

**Comment by scramble45** [comment]
So is there no way I can just override my local steam permissions so I can use this tool on a non-flatpak version of steam? The GUI version of this tool doesn't fit my use case I need to use it for a bash script to install a game without having to have the user interact.

**Comment by scramble45** [comment]
Nevermind, I appreciate the help but I just read that I can just use the script straight up and it does what I need it todo. Thanks agian!
