### ISSUE TITLE
SteamTinkerLaunch launch option for Native Linux Games

### ISSUE THREAD

**Issue by sonic2kk** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#40]
Hello!

To my understanding, it is not possible (or at least not straightforward) to use SteamTinkerLaunch as a launch option for native games when using SteamTinkerLaunch Flatpak. If this is incorrect, apologies for wasting your time.

Would it be possible to allow SteamTinkerLaunch to be used as a launch option for native games? Perhaps the SteamTinkerLaunch script could be added as an environment variable, if Steam Flatpak can see environment variables set by Flatpak. Regular Steam can't see environment variables unless they are set system-wide, but since Flatpak is sandboxed I was thinking this might be possible someway.

It would be really nifty if Flatpak users could use SteamTinkerLaunch with native games too by adding `steamtinkerlaunch %command%` to their launch options.

Thanks again for all the work maintaining STL Flatpak 😃

**Comment by HanPrower** [comment]
1. This already works as steamtinkerlaunch is available in the `/bin` folder
2. You can already force a tool for Linux games natively in Steam by right clicking a game > Properties > Compatibility > Force the use of a compatibility tool > Select Steam Tinker Launch

**Comment by sonic2kk** [comment]
Ah, I had just seen around the wiki that it didn't. I'll get the STL wiki updated. Thank you for the correction! :)
