### ISSUE TITLE
Is it possible to create a SteamTInkerLaunch Application Menu Icon?

### ISSUE THREAD

**Issue by sonic2kk** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#43]
Hey there!

I was going through the [SteamTinkerLaunch Flatpak wiki page](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Flatpak) and noticed that it mentions there is no application menu icon for STL Flatpak. I installed STL Flatpak and seemed to be able to verify that this is correct (KDE Plasma desktop).

I realise there may be external limitations here, but would it be possible to implement this? In KDE Menu Editor, other Flatpaks show their command as something along the lines of `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.foo.bar.blah`.

If it should be added as an application menu icon and I just missed it, very sorry and I can get the wiki page updated. If this is not possible, it's no worries, though if you could give even a brief outline of the reason that there is no application menu icon, it could be added to the wiki. And if it is possible but it's just low priority, that's no worries either :smiley: 

Thanks!

**Comment by HanPrower** [comment]
I never found a way to do it whilst creating the Flatpak, and I spent a long time trying.

This Flatpak is an extension/plugin of Steam, and Flatpak doesn't let you easily export the `.desktop` and relevant icon to appear in the applications menu for Flatpaks which are extensions/plugins of others.

I'm sure Flatpak probably has some way of doing it via a command, but it'd have to be integrated in to STL itself somehow to actually be leveraged.

It's not something I really want to take another look at as I haven't seen an actual Flatpak user request it yet.

**Comment by sonic2kk** [comment]
Thank you for the response! 

This sounds like even if it is possible, it's probably something best resolved with Flatpak upstream - That is, making it easier for extensions to have `.desktop` files. Even if STL could do it (which I'm not saying it *shouldn't*) it seems best resolved on the Flatpak side. I think there have been other discussions on Flatpak and Flathub issue trackers around improving support for extensions, like getting them to show up on the Flathub website, so probably not something that'll get fixed anytime soon.

The only thing I could think of to "resolve" this on STL's side is perhaps when it creates the `.desktop` file that it should pass the exec command as something like `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.valvesoftware.Steam.Utility.steamtinkerlaunch` and move it into the relevant Flatpak `.desktop` file folder (I think there's a specific/preferred one for Flatpak?), but something tells me there's gonna be more to it than that :sweat_smile: It would need tested too.

Once again, thanks for your time. If you don't mind I'll close this issue, no reason to keep it open. Your response gave the information needed and this probably isn't something that needs to be solved on the STL Flatpak end - From my understanding it would be ideally handled further upstream but it _could_ also be handled by STL.
