### ISSUE TITLE
Making it Clearer that Flatpak STL is only for Flatpak Steam?

### ISSUE THREAD

**Issue by sonic2kk** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#53]
Hi there, so I really hate to make this issue because this really isn't the fault of any of the maintainers here or any SteamTinkerLaunch contributors, but it's becoming a bit of a problem.

Several users have tried using Flatpak STL to install SteamTinkerLaunch on their Steam Decks. I would guess primarily that this is probably users who do not understand how to use Linux, don't know what a Flatpak is, and don't bother to read the notice you have kindly provided that tells them SteamTinkerLaunch Flatpak is **only for Flatpak Steam**.

This has led to a number of negative reviews (mostly from "Steam Deck User" :roll_eyes:) because users refuse to do any research into the tool they are using, and when it doesn't work they leave a bad review.

In my opinion, these negative reviews give a bad impression of SteamTinkerLaunch, and let me clear that I understand and want to emphasise that **this comes from user ignorance**. But the negative impression remains - SteamTinkerLaunch Flatpak in my tests works really well and delivers exactly what you all advertise - SteamTinkerLaunch for Flatpak Steam.

So I am making this issue to hopefully come up with some ideas on how to make it clearer to users that SteamTinkerLaunch is only for Flatpak Steam, and that they should not install it on their Steam Deck. I will be frank, it is irritating to see something that works great and something that took a lot of collaboration to get working, get negative reviews because of user error and user ignorance.

There is only so much one can do for a user that will not read the description of a tool they are downloading, but if there is any way we can think of to make it clearer that this is **not** for use on Steam Deck? While it irritates me, it is also irritating to end-users that can't understand why their tool isn't working, even though you have documented and I have personally [documented](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck#installation) [it in](https://github.com/sonic2kk/steamtinkerlaunch#how-do-i-install-it) [several](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#steam-flatpak) [places](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak#steam-flatpak) [already](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak#caveats).

A notice simply saying "Not for use on Steam Deck" might not do much good for the kinds of users who already do not read the description, and I've been thinking about it for a while and I can't come up with any ways to make it clearer, so I thought I would bring it to the attention of people over here and see if we can come up with any ideas!

Thanks! And for what it's worth, I am very sorry that your amazing work is being negatively reviewed by users that cannot understand how to use their operating system.

**Comment by HanPrower** [comment]
I assume some issues come from that fact that Flatpaks are the supported method for installing software on a Steam Deck? I've not looked in to the environment, I've just seem some random issues on /r/linux_gaming where people mention things.

From experience moderating communities I can tell you no amount of banners, warnings, READMEs, other threads/topics covering an issue will ever get people who are too lazy to a basic search to actually read anything beforehand. I will however add a note to the description that will show up on Discover anyway for those that do read.

As for those that do not read, my only idea, and it sucks, but I don't know how else you'd deal with it is to see if it can be detected if someone is using the Flatpak version of STL on a Steam Deck (or a Flatpak version of STL when there's no Flatpak Steam detected), and then instead of showing the main STL window just show a little pop-up that says along the lines "You're doing this wrong, please visit the wiki to do it right".

**Comment by sonic2kk** [comment]
I'm really sorry for the late reply, was caught up in a few things.

> From experience moderating communities I can tell you no amount of banners, warnings, READMEs, other threads/topics covering an issue will ever get people who are too lazy to a basic search to actually read anything beforehand. I will however add a note to the description that will show up on Discover anyway for those that do read.

This sounds about right, thanks for doing that though! I'm hoping it'll help at least a bit but I guess as well, there'll be that bias that the angry users are more likely to leave negative comments. But at the very least hopefully it'll serve as a warning for those "silent" users and save them a headache :-)

> As for those that do not read, my only idea, and it sucks, but I don't know how else you'd deal with it is to see if it can be detected if someone is using the Flatpak version of STL on a Steam Deck (or a Flatpak version of STL when there's no Flatpak Steam detected), and then instead of showing the main STL window just show a little pop-up that says along the lines "You're doing this wrong, please visit the wiki to do it right".

Oh gosh, this is actually a good idea and seems obvious now that I think about it. I wrote this down to remind myself and I'll look into some way to do this, I think this is possible. I believe STL has a few checks for running in a Flatpak so we should be able to show a dialog if we're running Flatpak STL and on Steam Deck.

I really appreciate your feedback here, and sorry if my initial issue was a little... Heated. I think this will be a good resolution though, your added notes and a dialog on the STL side should be good. I'll see about implementing this sometime this weekend, though no rush on updating the Flatpak or anything, it can probably wait until the next release.

Thanks again :-)
