### ISSUE TITLE
SpecialK needs 7za

### ISSUE THREAD

**Issue by Wiichele** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#73]
Found this line in the logs:
```
WARN - checkDep - Disabling 'USESPECIALK' because '7za' is missing
```
This command is in the Arch package of p7zip: https://archlinux.org/packages/extra/x86_64/p7zip/

**Comment by HanPrower** [comment]
I'll take a look at getting it added soon :+1:

**Comment by sonic2kk** [comment]
Let me know if there is anything needed on my side for this e.g. if the dependency check needs altered in any way for Flatpak :-)

**Comment by HanPrower** [comment]
Nope, I'm stupid. Yes, the `make install` wasn't meant to be there 😦

It was left over from when I was trying to clean up the process, and just forgot to remove it.

Fixed it with: https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/commit/43a943b6a9119bba40f12408f65c3e21c223d3a3

Build should be ready soon. Sorry about that... :face_exhaling:

**Comment by Wiichele** [comment]
No problem. Thanks for your time

**Comment by HanPrower** [comment]
So the update with `7za` in is finally available.

After I made the fix Flathub just seemed to refuse to publish new builds in general 🤔
