### ISSUE TITLE
Handling of nxm Links

### ISSUE THREAD

**Issue by Plamper** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#78]
It seems nxm links are not working right now as they should. I tried to run `flatpak enter com.valvesoftware.steam /app/utils/steamtinkerlaunch/bin/steamtinkerlaunch mo2 u %u` to attach to the flatpak but I would always get this warning: 
```
Sat Jan 28 12:40:36 CET 2023 ERROR - checkIntDeps - xrandr not found!

(yad:16153): Gtk-WARNING **: 12:40:36.266: cannot open display: 
Sat Jan 28 12:40:36 CET 2023 ERROR - checkIntDeps - Yad version '' is too old. You need to update to at least '7.2'
```
Steamtinkerlaunch works fine from steam itself and shows the GUI, so I think this should be possible.

**Comment by HanPrower** [comment]
So it dies at the YAD version check? That'd odd, because it definitely works...

```
flatpak run --command="yad" --file-forwarding com.valvesoftware.Steam --version | tail -n1 | cut -d ' ' -f1
12.3
```

Could you post your full log as it may make it more clear what's going on? Snippets are rarely helpful.

**Comment by Plamper** [comment]
I think I found the culprit flatpak enter runs as root inside the sandbox. The problem still remains because flatpak run creates a new separate sandbox where it can't find the running steamtinkerlaunch.

**Comment by HanPrower** [comment]
`flatpak run --command="steamtinkerlaunch" --file-forwarding com.valvesoftware.Steam mo2 u %u`

Seems to work fine.

**Comment by Plamper** [comment]
Yes this appears to work but only if steamtinkerlaunch is also started with flatpak run too.

**Comment by HanPrower** [comment]
That's not true. As long as the Steam Flatpak is running any commands will work as I've demonstrated. This STL Flatpak relies on that runtime running to work correctly.

I'm going to close this as I'm not really sure what you're expecting me to do.
