### ISSUE TITLE
Not appearing as a option in steam.

### ISSUE THREAD

**Issue by TheGreatestJannet** [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#93]
I have installed it but in flatpak steam it doesn't appear and can't be chosen. I have the latest version of flatpak steam and flatpak steamtinkerlaunch.

This has been happening for a while now but haven't gotten around to opening a bug report.

**Comment by HanPrower** [comment]
Due to the nature of how Flatpak's work this doesn't really make sense.

The Steam flatpak exposes the `compatibility.d` folder, and SteamTinkerLaunch installs its files there.

The only thing I can imagine is you're using something like Flatseal to mess with the permissions.

**Comment by TheGreatestJannet** [comment]
Thanks I reset the permissions and that fixed it!

**Comment by Yaakoss** [comment]
Fresh install of Debian Bookworm (today) . New Steam Flatpak and SteamTinkerLaunch. No other Flatpaks Apps installed. 
SteamTinkerLaunch is not showing up.
Nothing has been changed with the permissions of the flatpaks. All default settings.
